# Generated by Django 6.0.1 on 2026-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment_customer_name_appointment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
