# Generated by Django 6.0.1 on 2026-03-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Visit Us', max_length=150)),
                ('address', models.TextField(default='K-5, Kalinga Vihar LIG, Kalinganagar, Bhubaneswar, Odisha – 751028')),
                ('opening_days', models.CharField(default='Monday – Sunday', max_length=100)),
                ('opening_time', models.CharField(default='10:00 AM', max_length=50)),
                ('closing_time', models.CharField(default='9:00 PM', max_length=50)),
                ('map_query', models.CharField(default='K-5, Kalinga Vihar LIG, Kalinganagar, Bhubaneswar, Odisha 751028', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
