# Generated by Django 6.0.1 on 2026-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Optional: direct Google Maps link (e.g., https://maps.app.goo.gl/...) — takes precedence over map_query.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='map_query',
            field=models.CharField(default='K-5, Kalinga Vihar LIG, Kalinganagar, Bhubaneswar, Odisha 751028', help_text='Address, coordinates, or place ID used for map embedding and directions.', max_length=500),
        ),
    ]
